
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package hpl.lang;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 12;
  public static final int MOD = 14;
  public static final int ELSE = 32;
  public static final int FRAME = 6;
  public static final int PLUS = 10;
  public static final int RPAREN = 16;
  public static final int IN = 22;
  public static final int SEMI = 19;
  public static final int PAINT = 3;
  public static final int NOT = 33;
  public static final int END = 23;
  public static final int DEF_PAINTER = 2;
  public static final int IF = 31;
  public static final int COLON = 21;
  public static final int LBRACKET = 17;
  public static final int LPAREN = 15;
  public static final int IMG_PAINTER = 5;
  public static final int RBRACKET = 18;
  public static final int SUBFRAME = 7;
  public static final int STRING = 28;
  public static final int COMMA = 20;
  public static final int CMP = 29;
  public static final int EOF = 0;
  public static final int DIV = 13;
  public static final int MINUS = 11;
  public static final int error = 1;
  public static final int LET = 8;
  public static final int ASSIGN = 4;
  public static final int INTEGER = 24;
  public static final int LCMP = 30;
  public static final int REAL = 26;
  public static final int FRACTION = 25;
  public static final int VAR = 27;
  public static final int WAIT = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DEF_PAINTER",
  "PAINT",
  "ASSIGN",
  "IMG_PAINTER",
  "FRAME",
  "SUBFRAME",
  "LET",
  "WAIT",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "MOD",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "SEMI",
  "COMMA",
  "COLON",
  "IN",
  "END",
  "INTEGER",
  "FRACTION",
  "REAL",
  "VAR",
  "STRING",
  "CMP",
  "LCMP",
  "IF",
  "ELSE",
  "NOT"
  };
}

